# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  name: truthfullspool

resources:
  repositories:
  - repository:  ui
    type: github
    endpoint: mtaronji
    name: mtaronji/truthfullsUI

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: BuildStage
  jobs:
  - job: Build
    displayName: "Test and Build"
    steps:
    - checkout: self
    - checkout: UI
    - task: NuGetToolInstaller@1
      displayName: "Install Nuget"
      
    - task: UseDotNet@2 
      displayName: ".Install NET Core 6.x"
      inputs:
        version: '6.x'
        packageType: sdk

    - script: |
              echo $(System.DefaultWorkingDirectory)
              cd $(System.DefaultWorkingDirectory)/truthfullswebapi
              dotnet build --configuration $(buildConfiguration)
      displayName: 'Build App'
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.RootDirectory)/testdata
        Contents: |
                *.db
        TargetFolder: $(System.DefaultWorkingDirectory)/truthfullswebapi/TruthfullsTests
      displayName: "Copying unit test db to the pipeline to run tests"
    - script: |
               echo $(System.DefaultWorkingDirectory)
               cd $(System.DefaultWorkingDirectory)/truthfullswebapi
               dotnet test
      displayName: 'Testing WEB API'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
      displayName: "Publishing webapi to artifact staging"
    - script: |
              cd $(Build.ArtifactStagingDirectory)/truthfulls.com
              mkdir app_data
      displayName: "Creating app_data directory"

    - task: NodeTool@0
      inputs:
        versionSpec: 18.10.x
      displayName: "Install node 18.10.x"
    - script: |
              cd $(System.DefaultWorkingDirectory)/truthfullsUI
              npm ci 
              npm install -g @angular/cli
              ng build
      displayName: "Installing npm, angular and building the UI"
    - script: |
              echo $(System.DefaultWorkingDirectory)
              cd $(System.DefaultWorkingDirectory)/truthfullsUI
              ng test TruthfullsUI --code-coverage --karma-config karma.conf.ci.js 
      displayName: "running tests on UI"
      
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)/truthfullsUI/dist
        TargetFolder: $(Build.ArtifactStagingDirectory)/truthfulls.com
      displayName: "Copying Angular build to Artifact staging directory"
      
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.RootDirectory)/Data
        TargetFolder: $(Build.ArtifactStagingDirectory)/truthfulls.com/Data
      displayName: "Copying SQL lite production DB"
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.ArtifactStagingDirectory)/truthfulls.com
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/truthfulls.zip
    - script: |
              rm -r -f $(Build.ArtifactStagingDirectory)/truthfulls.com
      displayName: "Cleanup"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'truthfulls'
      displayName: "Creating webapi Artifact"


  
