# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  name: truthfullspool

resources:
  repositories:
  - repository:  ui
    type: github
    name: mtaronji/truthfullsUI

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: BuildStage
  jobs:
  - job: BuildWebAPI
    steps:
    - checkout: self
    - checkout: UI
    - task: NuGetToolInstaller@1
      displayName: "Install Nuget"  
    - task: UseDotNet@2 
      displayName: ".Install NET Core 6.x"
      inputs:
        version: '6.x'
        packageType: sdk

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build App'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'truthfullpublish'


- stage: TestStage
  jobs:
  - job: TestWebAPI
    displayName: "Testing WebAPI"
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.RootDirectory)/testdata
        Contents: |
                *.db
        TargetFolder: $(Pipeline.Workspace)/s/TruthfullsTests
      displayName: "Copying unit test db to the pipeline to run tests"

    - script: dotnet test --configuration Release --no-build
      displayName: "Running the Web API Tests"



  
