# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: truthfullspool


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: "Install Nuget"
  
- task: UseDotNet@2 
  displayName: ".NET Core 6.x"
  inputs:
    version: '6.x'
    packageType: sdk
    
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths).
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.RootDirectory)/*.db
    Contents: '**' # string. Required. Contents. Default: **.
    TargetFolder: $(Pipeline.Workspace)/s/TruthfullsTests
  displayName: "Copying unit test db to the pipeline."

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build App'

- script: dotnet test --configuration Release --no-build
  displayName: "Running the Web API Tests"